### ISSUE TITLE
Promotion of specific tool in animated images tutorial 

### ISSUE THREAD

**Issue by JamieKnightBBC** [bbc/a11y-tuts#5]
Less of an issue, more of a placeholder for a discussion. The animated images tutorial includes a mention of a team developed tool for testing GIF's.

"If you don't already have a tool to measure looping in your GIF, try out my <abbr title="free and open source software">FOSS</abbr> project [Gif-scrape](https://github.com/micmath/gif-scrape)."

This poses a few questions:

1. Should we recommend a tool?
2. Should we recommend a list of tools (eg, plugins for sketch, as well a cli tools)
3. If we do, are we allowed to have a personal tool included in the list (and if so, does it need disclaimers etc)

It may also be better for the tutorial to take a de-presonal tone.

**Comment by micmath** [comment]
Good questions!

1. Yes recommending tools seems perfectly appropriate for a _tutorial_ (although not necessarily for a _guideline_ and definitely not for a _standard_).
2. Yes, a list of tools that can do the equivalent job would be great. I would have to rely on others to provide those links though since I personally know of none myself.
3. Agree the possible issues with what you are calling a "personal tool."  Ideally I think it should be moved into a `bbc/a11y-*` repo and considering the amount of value the BBC gains from FOSS it would seem weird _not_ to make such tools available.

Re disclaimers, this moves the discussion quickly into the "How should BBC do open source" area, which has already been beaten to death elsewhere. I can find out what other teams do and follow that as an example.

**Comment by micmath** [comment]
In order to help find equivalent alternative suggestions, and to lay out the reason of including the `gif-scrape` tool in the tutorial, this explanation:

The WCAG Guidelines† provide helpful and simple mathematical formulas for determining looping compliance, but don't show how to actually get the values to use in the formula. When dealing with limits as fine as the difference between 4.5 and 5.5 seconds, it would be unreasonable to expect a human to gather those measurements by simply looking and clicking a stopwatch for example. And also unnecessary since the actual exact values are explicitly encoded within the image file itself. So the required functionality of an equivalent tool would be to simply expose those values, which presumably would then be plugged into the WCAG formula.

† see https://www.w3.org/TR/WCAG20-TECHS/G152.html

**Comment by EmmaJP** [comment]
The BBC-wide advocacy stuff on Confluence and Slack has some info on open source. bbc-a11y is effectively open source, so I'm aware there are forms to complete and licensing stuff to consider and work out/include.

Do the tools for creating an animated GIF not provide the information the user needs? I've used Fireworks to do so in the past, and have always had a good idea from that how long the animation would be and how many times it would loop.
